{
    'name':'asistencia de trabajador',
    'autor':'Johao',
    'depends':[
        'base'
    ],
    'data':[
        'views/asistencia_views.xml',
        'wizard/wizard_asistencia_user.xml',
        'views/asistencia_menu.xml',
        #security
        'security/res_groups.xml',
        'security/ir_model_access.xml',
        #report
        'report/report_asistencia_user.xml',
        'report/report_wizard_asistencia_user.xml',
        'report/reports.xml'
    ]
}